name: Bug Report
description: Report a bug with Cascade Climate
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
    validations:
      required: true

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: "2025.11.2"
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: Integration Version
      description: What version of Cascade Climate are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please provide your integration configuration (sanitize any sensitive data)
      placeholder: |
        Room sensor: sensor.living_room_temperature
        Radiator sensor: sensor.radiator_temperature
        Pump switch: switch.heating_pump
        ...
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please provide relevant logs. Enable debug logging:
        ```yaml
        logger:
          logs:
            custom_components.cascade_climate: debug
        ```
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, etc.)
