name: Feature Request
description: Suggest an idea for Cascade Climate
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this form as completely as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature relate to?
      options:
        - Control Algorithm (PI tuning, hysteresis, etc.)
        - Observer/Estimation (radiator temperature estimation)
        - Configuration (new parameters, UI improvements)
        - Sensors/Entities (new sensors, attributes)
        - Integration (HACS, Home Assistant compatibility)
        - Documentation
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
